[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["src/**", "prisma/**", "package.json", "tsconfig.json"]

[deploy]
startCommand = "node --experimental-crypto-policy=default dist/main.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5 